config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),

    # User management
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    # Local apps
    path('accounts/', include('users.urls')),
    path('', include('home.urls')),
    path('rooms/', include('rooms.urls')),
    path('newsletters/', include('newsletter.urls')),

]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home')
]

newsletter/urls.py
from django.urls import path

from newsletter import views

urlpatterns = [
    path('', views.NewsletterPage.as_view(), name='newsletter')
]

rooms/urls.py
from django.urls import path

from rooms import views

urlpatterns = [
    path('', views.rooms_view, name='rooms')
]

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('signup/', views.SignupPageView.as_view(), name='signup')
]

home/models.py
from django.db import models

# Create your models here.

newsletter/models.py
from django.db import models


class NewsletterUser(models.Model):
    email = models.EmailField(unique=True)
    added = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField('NewsletterCategory', through='Agreement', related_name='users_categories')

    def __str__(self):
        return self.email


class NewsletterCategory(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField()
    required = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.name


class AgreementLog(models.Model):
    updated_at = models.DateTimeField(auto_now_add=True)
    agreement = models.ForeignKey('Agreement', on_delete=models.DO_NOTHING, related_name='log')
    status = models.BooleanField()

    def __str__(self):
        return f'Agreement: {self.agreement}, updated at: {self.updated_at:%d-%m-%y}, status: {self.status}'


class AgreementManager(models.query.QuerySet):
    def update(self, **kwargs):
        super().update(**kwargs)
        AgreementLog.objects.bulk_create([
            AgreementLog(agreement=agreement, status=agreement.agreed) for agreement in self
        ])


class Agreement(models.Model):
    category = models.ForeignKey('NewsletterCategory', on_delete=models.DO_NOTHING, related_name='agreement_category')
    email = models.ForeignKey('NewsletterUser', on_delete=models.DO_NOTHING, related_name='agreement_email')
    agreed = models.BooleanField(default=False)

    objects = AgreementManager.as_manager()

    def __str__(self):
        return f'Email: {self.email}, category: {self.category}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        AgreementLog.objects.create(agreement=self, status=self.agreed)

rooms/models.py
from django.db import models


class Availability(models.Model):
    class Meta:
        verbose_name = 'Availability'
        verbose_name_plural = 'Availabilities'

    class BookType(models.IntegerChoices):
        APPOINTMENT = 1
        ADMINISTRATION = 2
        OTHER = 3

    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    duration = models.DurationField()
    book_type = models.IntegerField(choices=BookType.choices)

    def __str__(self):
        return f'{self.room}'


class Room(models.Model):
    floor = models.SmallIntegerField()
    room_no = models.SmallIntegerField()

    def __str__(self):
        return f'Room {self.room_no} on floor {self.floor}'

users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models


class Nationality(models.Model):
    iso = models.CharField(max_length=2)
    full_name = models.CharField(max_length=56)


class QueuePriority(models.Model):
    name = models.CharField(max_length=30)
    level = models.IntegerField(default=0, help_text="Higher is more important. Add levels with big tiers.")


class Address(models.Model):
    street = models.CharField(max_length=50)
    building_number = models.CharField(max_length=5)
    flat_number = models.CharField(max_length=5, blank=True, null=True)
    zip_code = models.CharField(max_length=6)
    city = models.CharField(max_length=85)
    country = models.CharField(max_length=56)
    address_type = models.IntegerChoices('Address', 'address correspondence billing registered shipping')


class Specialization(models.Model):
    specialization = models.CharField(max_length=50)


class CustomUser(AbstractUser):
    class GenderType(models.IntegerChoices):
        MALE = 1
        FEMALE = 2
        RATHER_NOT_SAY = 3

    personal_identity_number = models.CharField(max_length=50)
    nationality = models.ForeignKey('Nationality', on_delete=models.DO_NOTHING, related_name='users')
    birthday = models.DateField()
    gender = models.IntegerField(choices=GenderType.choices)
    is_doctor = models.BooleanField(default=False)
    queue_priority = models.ForeignKey('QueuePriority', default=1,
                                       on_delete=models.SET_DEFAULT, related_name='users')
    address = models.ManyToManyField('Address', related_name='user_address', through='CustomUserAddress')
    specialization = models.ManyToManyField('Specialization', blank=True)


class CustomUserAddress(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(get_user_model(), related_name='user_address', on_delete=models.DO_NOTHING)
    address = models.ForeignKey('Address', related_name='address_user', on_delete=models.DO_NOTHING)

newsletter/forms.py
from django import forms

from newsletter.models import NewsletterUser, NewsletterCategory, Agreement


class NewsletterUserForm(forms.ModelForm):
    class Meta:
        model = NewsletterUser
        fields = ('email', 'categories')

    query = NewsletterCategory.objects.all
    categories = forms.ModelMultipleChoiceField(queryset=query(),
                                                widget=forms.CheckboxSelectMultiple)

    def save(self, commit=True):
        obj = super().save(commit=True)
        agreements = Agreement.objects.filter(email=obj).update(agreed=True)

        return obj

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home/home.html'

# def home_page_view(request):
#     return render(request, 'home/home.html')

newsletter/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView

from newsletter.forms import NewsletterUserForm
from newsletter.models import NewsletterUser


class NewsletterPage(FormView):
    form_class = NewsletterUserForm
    template_name = 'newsletter/newsletter.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

rooms/views.py
from django.shortcuts import render

from rooms.models import Room


def rooms_view(request):
    rooms = Room.objects.prefetch_related('availability_set')
    return render(request, 'rooms/rooms.html', {"rooms": rooms})

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import CustomUserCreationForm


class SignupPageView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

home/templates/home/home.html
{% extends '_base.html' %}

{% block title %}- Home{% endblock %}

{% block content %}

    <div class="container">
        <h1 class="hdl-primary">Welcome Home</h1>

        {% if user.is_authenticated %}
            Hi {{ user.email }}
            <p>
                <a href="{% url 'account_logout' %}" class="btn btn-success">Logout</a>
            </p>
        {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'account_signup' %}" class="btn btn-success">Sign Up</a>
            <a href="{% url 'account_login' %}" class="btn btn-success">Log In</a>

        {% endif %}

    </div>


{% endblock %}

newsletter/templates/newsletter/newsletter.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Newsletter</h2>
    <form action="" method="post">

        {% csrf_token %}
        {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Add me</button>

    </form>

{% endblock %}

rooms/templates/rooms/rooms.html
{% extends '_base.html' %}
{% load custom_template_tags %}

{% block title %}- Rooms{% endblock %}

{% block content %}

    <div class="container">
        <h1 class="hdl-primary">Rooms list</h1>


        <ol class="list-group list-group-numbered">
            {% for room in rooms %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">Room number: {{ room.room_no }}</div>
                        {% for av in  room.availability_set.all %}

                            <div class="mb-2">
                                <span class="badge rounded-pill bg-{% make_color av.book_type %}">{{ av.get_book_type_display }}</span>
                                {{ av.start_date }}
                                {{ av.duration }}
                            </div>

                        {% endfor %}
                    </div>
                    <span class="badge bg-primary rounded-pill">{{ room.floor }} floor</span>
                </li>
            {% empty %}
                <li>No rooms added yet.</li>
            {% endfor %}
        </ol>

    </div>


{% endblock %}

templates/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>iDoctor {% block title %}{% endblock %}</title>
    {% block styles %}
        <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock %}
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img class="logo" src="{% static 'images/logo.svg' %}" alt="Logo iDoctor">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'rooms' %}">Rooms</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'newsletter' %}">Newsletter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">Placówki</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Kontakt</a>
                    </li>
                </ul>
                <div class="flex">
                    {% if user.is_authenticated %}
                        Witaj, {{ user.email }}
                        <p>
                            <a href="{% url 'account_logout' %}" class="nav-link">Logout</a>
                        </p>
                    {% else %}
                        <p>You are not logged in</p>
                        <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
                        <a href="{% url 'account_login' %}" class="nav-link">Log In</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

</header>


<div class="container mt-3">
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>


{% block scripts %}
    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'scripts/app.js' %}"></script>
{% endblock %}
</body>
</html>